version: '3.8'

services:
web:
    image: economie:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
 

  # MySQL service
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_1
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    ports:
      - "3308:3307" # Exposing MySQL port 3307 on localhost
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80" # Exposing phpMyAdmin on localhost port 8081
    depends_on:
      - db

volumes:
  db_data: # Persistent storage for MySQL data